server:
  port: 8082

spring:
  application:
    name: mini-arch

# 自定义中间件配置
net.tianzx:
  arch:
    scheudle:
      zkAddress: 127.0.0.1:2181
      schedulerServerId: schedule-mini-schedule-test
      schedulerServerName: 分布式任务测试
